# Generated by Django 5.1.2 on 2024-11-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_favourite_recipes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cooking_level',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cooking_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
    ]
