# Generated by Django 5.1.2 on 2024-11-20 18:06

import CoockingWebsite.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[CoockingWebsite.accounts.validators.OnlyLettersValidator()]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[CoockingWebsite.accounts.validators.OnlyLettersValidator()]),
        ),
    ]
