# Generated by Django 5.1.2 on 2024-11-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_preparations_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=200),
        ),
    ]
